set_property SRC_FILE_INFO {cfile:/home/selena/TopmetalSe_Sequencer/TopmetalSe_Sequencer.srcs/constrs_1/imports/new/topmetal-fpga-constraints.xdc rfile:../TopmetalSe_Sequencer.srcs/constrs_1/imports/new/topmetal-fpga-constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets RESET_IBUF]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets EXTERN_CLK_IBUF]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets EXTERN_CLK_IBUF_BUFG]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports {ADC_VAL[6]}]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M18 [get_ports {ADC_VAL[4]}]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N17 [get_ports {ADC_VAL[2]}]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P18 [get_ports {ADC_VAL[0]}]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L17 [get_ports {ADC_VAL[7]}]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M19 [get_ports {ADC_VAL[5]}]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P17 [get_ports {ADC_VAL[3]}]
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R18 [get_ports {ADC_VAL[1]}]
set_property src_info {type:XDC file:1 line:438 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:446 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:448 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list EXTERN_CLK_IBUF_BUFG]]
set_property src_info {type:XDC file:1 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:450 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:451 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {CLK_SEQ/ADC_IN[0]} {CLK_SEQ/ADC_IN[1]} {CLK_SEQ/ADC_IN[2]} {CLK_SEQ/ADC_IN[3]} {CLK_SEQ/ADC_IN[4]} {CLK_SEQ/ADC_IN[5]} {CLK_SEQ/ADC_IN[6]} {CLK_SEQ/ADC_IN[7]}]]
set_property src_info {type:XDC file:1 line:452 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:455 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {CLK_SEQ/trigger_threshold[0]} {CLK_SEQ/trigger_threshold[1]} {CLK_SEQ/trigger_threshold[2]} {CLK_SEQ/trigger_threshold[3]}]]
set_property src_info {type:XDC file:1 line:456 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:458 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:459 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {CLK_SEQ/adc_in_buf_2[0]} {CLK_SEQ/adc_in_buf_2[1]} {CLK_SEQ/adc_in_buf_2[2]} {CLK_SEQ/adc_in_buf_2[3]} {CLK_SEQ/adc_in_buf_2[4]} {CLK_SEQ/adc_in_buf_2[5]} {CLK_SEQ/adc_in_buf_2[6]} {CLK_SEQ/adc_in_buf_2[7]}]]
set_property src_info {type:XDC file:1 line:460 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:462 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:463 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {CLK_SEQ/adc_val_prev_frame[0]} {CLK_SEQ/adc_val_prev_frame[1]} {CLK_SEQ/adc_val_prev_frame[2]} {CLK_SEQ/adc_val_prev_frame[3]} {CLK_SEQ/adc_val_prev_frame[4]} {CLK_SEQ/adc_val_prev_frame[5]} {CLK_SEQ/adc_val_prev_frame[6]} {CLK_SEQ/adc_val_prev_frame[7]}]]
set_property src_info {type:XDC file:1 line:464 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:466 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:467 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {CLK_SEQ/diff[0]} {CLK_SEQ/diff[1]} {CLK_SEQ/diff[2]} {CLK_SEQ/diff[3]} {CLK_SEQ/diff[4]} {CLK_SEQ/diff[5]} {CLK_SEQ/diff[6]} {CLK_SEQ/diff[7]}]]
set_property src_info {type:XDC file:1 line:468 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:470 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:471 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {CLK_SEQ/pxl_addr[0]} {CLK_SEQ/pxl_addr[1]} {CLK_SEQ/pxl_addr[2]} {CLK_SEQ/pxl_addr[3]} {CLK_SEQ/pxl_addr[4]} {CLK_SEQ/pxl_addr[5]} {CLK_SEQ/pxl_addr[6]} {CLK_SEQ/pxl_addr[7]} {CLK_SEQ/pxl_addr[8]} {CLK_SEQ/pxl_addr[9]} {CLK_SEQ/pxl_addr[10]} {CLK_SEQ/pxl_addr[11]} {CLK_SEQ/pxl_addr[12]} {CLK_SEQ/pxl_addr[13]} {CLK_SEQ/pxl_addr[14]} {CLK_SEQ/pxl_addr[15]} {CLK_SEQ/pxl_addr[16]} {CLK_SEQ/pxl_addr[17]} {CLK_SEQ/pxl_addr[18]} {CLK_SEQ/pxl_addr[19]} {CLK_SEQ/pxl_addr[20]} {CLK_SEQ/pxl_addr[21]} {CLK_SEQ/pxl_addr[22]} {CLK_SEQ/pxl_addr[23]} {CLK_SEQ/pxl_addr[24]} {CLK_SEQ/pxl_addr[25]} {CLK_SEQ/pxl_addr[26]} {CLK_SEQ/pxl_addr[27]} {CLK_SEQ/pxl_addr[28]} {CLK_SEQ/pxl_addr[29]} {CLK_SEQ/pxl_addr[30]} {CLK_SEQ/pxl_addr[31]}]]
set_property src_info {type:XDC file:1 line:472 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:474 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:475 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {CLK_SEQ/pxl_addr_next[0]} {CLK_SEQ/pxl_addr_next[1]} {CLK_SEQ/pxl_addr_next[2]} {CLK_SEQ/pxl_addr_next[3]} {CLK_SEQ/pxl_addr_next[4]} {CLK_SEQ/pxl_addr_next[5]} {CLK_SEQ/pxl_addr_next[6]} {CLK_SEQ/pxl_addr_next[7]} {CLK_SEQ/pxl_addr_next[8]} {CLK_SEQ/pxl_addr_next[9]} {CLK_SEQ/pxl_addr_next[10]} {CLK_SEQ/pxl_addr_next[11]} {CLK_SEQ/pxl_addr_next[12]} {CLK_SEQ/pxl_addr_next[13]} {CLK_SEQ/pxl_addr_next[14]} {CLK_SEQ/pxl_addr_next[15]} {CLK_SEQ/pxl_addr_next[16]} {CLK_SEQ/pxl_addr_next[17]} {CLK_SEQ/pxl_addr_next[18]} {CLK_SEQ/pxl_addr_next[19]} {CLK_SEQ/pxl_addr_next[20]} {CLK_SEQ/pxl_addr_next[21]} {CLK_SEQ/pxl_addr_next[22]} {CLK_SEQ/pxl_addr_next[23]} {CLK_SEQ/pxl_addr_next[24]} {CLK_SEQ/pxl_addr_next[25]} {CLK_SEQ/pxl_addr_next[26]} {CLK_SEQ/pxl_addr_next[27]} {CLK_SEQ/pxl_addr_next[28]} {CLK_SEQ/pxl_addr_next[29]} {CLK_SEQ/pxl_addr_next[30]} {CLK_SEQ/pxl_addr_next[31]}]]
set_property src_info {type:XDC file:1 line:476 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:478 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:479 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets INTERN_CLK_IBUF_BUFG]
