#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Apr 28 11:54:34 PDT 2025
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim trigger_tb_behav -key {Behavioral:trigger_tb:Functional:trigger_tb} -tclbatch trigger_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/selena/TopmetalSe_Sequencer/trigger_tb_behav.wcfg -log simulate.log"
xsim trigger_tb_behav -key {Behavioral:trigger_tb:Functional:trigger_tb} -tclbatch trigger_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/selena/TopmetalSe_Sequencer/trigger_tb_behav.wcfg -log simulate.log

